import type { Metadata } from "next";
import { Oswald } from "next/font/google";
import "./sass/all.scss";
import NavBar from "./components/navbar/nav";
import Hero from "./components/hero/hero";
import SmoothScroll from "./components/scroll/smoothScroll";
const oswald = Oswald({ subsets: ["latin"], weight: ["200", "400", "700"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={oswald.className}>
        <SmoothScroll>
          <NavBar />
          <Hero />
          {children}
        </SmoothScroll>
      </body>
    </html>
  );
}
